#!/bin/bash
#programa usando case

echo "Introduzca un numero del 1 al 10"
read n
case $n in
1) echo "I";;
2) echo "II";;
3) echo "III";;
4) echo "IV";;
5) echo "V";;
6) echo "VI";;
7) echo "VII";;
8) echo "VIII";;
9) echo "IX";;
10) echo "X";;
esac
