#!/bin/bash
#funcion factorial

function factorial(){
local f
local i
i=1
f=1
while [ $i -le $1 ]
do
f=$((f * i))
i=$((i + 1))
done
return $f
}

read -p "digite un numero: " n
factorial $n

echo "el factorial es: " $?
